# Generated by Django 3.0.8 on 2020-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieID', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('elo', models.FloatField(default=1000)),
                ('image_url', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
